# Generated by Django 6.0.4 on 2026-05-15 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='historialdocumento',
            name='documento',
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='cliente_nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='documento_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estadodocumento',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
