# Generated by Django 6.0.4 on 2026-05-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_remove_documento_modificado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='estatus_doc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='tipo_tramite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HistorialDocumento',
        ),
    ]
